spring.application.name=expense-claim-workflow
server.port=8080
spring.profiles.active=h2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.problemdetails.enabled=false
